### ISSUE TITLE
use-named-exports throws on FunctionDeclarations

### ISSUE THREAD

**Issue by seansfkelley** [JamieMason/codemods#17]
## Description

Running `use-named-exports` on this:

```ts
export default function foo(){}
```

throws:

```
 ERR file.js Transformation error ({ type: FunctionDeclaration, start: 15, end: 32, loc: null, id: [object Object], generator: false, async: false, params: , body: [object Object], expression: false, defaults: , rest: null, returnType: null, typeParameters: null, predicate: null } does not match field "init": Expression | null of type VariableDeclarator)
Error: { type: FunctionDeclaration, start: 15, end: 32, loc: null, id: [object Object], generator: false, async: false, params: , body: [object Object], expression: false, defaults: , rest: null, returnType: null, typeParameters: null, predicate: null } does not match field "init": Expression | null of type VariableDeclarator
    at addParam (/Users/seankelley/code/codemods/node_modules/ast-types/lib/types.js:450:27)
    at /Users/seankelley/code/codemods/node_modules/ast-types/lib/types.js:473:25
    at Array.forEach (<anonymous>)
    at Function.variableDeclarator (/Users/seankelley/code/codemods/node_modules/ast-types/lib/types.js:471:35)
    at Collection.exportDefaultAsNamed (/Users/seankelley/code/codemods/transforms/lib/helpers.js:160:73)
    at NodePath.<anonymous> (/Users/seankelley/code/codemods/transforms/use-named-exports.js:26:33)
    at NodePath.<anonymous> (/Users/seankelley/code/codemods/node_modules/jscodeshift/src/collections/Node.js:156:49)
    at /Users/seankelley/code/codemods/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/seankelley/code/codemods/node_modules/jscodeshift/src/Collection.js:74:18)
```

## Suggested Solution

Rewrite to the following:

```ts
export function foo(){}
```

or (assuming the file is called `bar.js` and we're doing the rename-export-after-file thing):

```ts
export function bar(){}
```

## Help Needed

I'm not very familiar with jscodeshift so I hacked this poorly onto a fork of mine at https://github.com/seansfkelley/codemods/commit/bb28f9ed4cb865459ccfc3e22a35029c0c8bb95a.

It performs the second modification above, that is, to rename the exported function after the file.

I'm filing this issue to help anyone else who might stumble upon the same error. Thank you so much for publishing this repo; you saved me a bunch of work!

**Comment by JamieMason** [comment]
Looks good Sean, thanks a lot. When I get some time I'll try and get that merged in 👍🏻

**Comment by lcswillems** [comment]
Hey @JamieMason , encountering the same issue on my side, making the codemod unusable. 100% of our default exports are this way.
